import React, { useState, useEffect, useRef } from 'react';
import { useAppContext } from '../contexts/AppContext';
import {
  XIcon,
  SaveIcon,
  FolderIcon,
  PlusIcon,
  CopyIcon,
  ClipboardCheckIcon,
  ChevronDownIcon,
} from './icons';

const SimpleMarkdownRenderer: React.FC<{ content: string }> = ({ content }) => {
  // This is a basic renderer and does not cover all Markdown features.
  // It's designed to handle the format generated by the app.
  const renderInline = (text: string) => {
    // A simple regex for links and bold within a paragraph
    const parts = text.split(/(\[.*?\]\(.*?\))|(\*\*.*?\*\*)/g).filter(Boolean);
    return (
      <>
        {parts.map((part, j) => {
          const linkMatch = part.match(/\[(.*?)\]\((.*?)\)/);
          if (linkMatch) {
            return (
              <a key={j} href={linkMatch[2]} target="_blank" rel="noopener noreferrer">
                {linkMatch[1]}
              </a>
            );
          }
          const boldMatch = part.match(/\*\*(.*?)\*\*/);
          if (boldMatch) {
            return <strong key={j}>{boldMatch[1]}</strong>;
          }
          return part;
        })}
      </>
    );
  };

  const blocks = content.split('\n');
  const renderedElements: React.ReactNode[] = [];
  let listItems: string[] = [];

  const flushList = () => {
    if (listItems.length > 0) {
      renderedElements.push(
        <ul key={`ul-${renderedElements.length}`} className="list-disc pl-5 space-y-1">
          {listItems.map((item, idx) => (
            <li key={idx}>{renderInline(item)}</li>
          ))}
        </ul>
      );
      listItems = [];
    }
  };

  blocks.forEach((line, i) => {
    const imageMatch = line.match(/^!\[(.*?)\]\((.*?)\)$/);
    if (imageMatch) {
      flushList();
      renderedElements.push(
        <img
          key={i}
          alt={imageMatch[1]}
          src={imageMatch[2]}
          className="max-w-full h-auto rounded-md my-4"
        />
      );
    } else if (line.startsWith('## ')) {
      flushList();
      renderedElements.push(<h2 key={i}>{renderInline(line.substring(3))}</h2>);
    } else if (line.startsWith('### ')) {
      flushList();
      renderedElements.push(<h3 key={i}>{renderInline(line.substring(4))}</h3>);
    } else if (line.startsWith('- ')) {
      listItems.push(line.substring(2));
    } else if (line.trim() === '---') {
      flushList();
      renderedElements.push(<hr key={i} />);
    } else if (line.trim() === '') {
      flushList();
      renderedElements.push(<br key={i} />);
    } else {
      flushList();
      renderedElements.push(<p key={i}>{renderInline(line)}</p>);
    }
  });

  flushList(); // Make sure to render any list at the end

  return (
    <div className="prose prose-invert max-w-none prose-p:text-gray-300 prose-headings:text-white prose-a:text-indigo-400">
      {renderedElements}
    </div>
  );
};

export const NoteEditorModal: React.FC = () => {
  const {
    isNoteEditorModalOpen,
    handleCloseNoteEditor,
    noteToEdit,
    initialNoteContent,
    handleSaveNote,
    noteFolders,
    handleAddNoteFolder,
  } = useAppContext();

  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [folderId, setFolderId] = useState<string>('');
  const [sourceArticleIds, setSourceArticleIds] = useState<{ feedId: string; articleId: string }[]>(
    []
  );
  const [showNewFolderInput, setShowNewFolderInput] = useState(false);
  const [newFolderName, setNewFolderName] = useState('');
  const titleInputRef = useRef<HTMLInputElement>(null);
  const [isCopyDropdownOpen, setIsCopyDropdownOpen] = useState(false);
  const [copyStatus, setCopyStatus] = useState<'idle' | 'copied' | 'error'>('idle');
  const copyDropdownRef = useRef<HTMLDivElement>(null);
  const [mode, setMode] = useState<'edit' | 'view'>('edit');

  useEffect(() => {
    if (isNoteEditorModalOpen) {
      if (noteToEdit) {
        setTitle(noteToEdit.title);
        setContent(noteToEdit.content);
        setFolderId(noteToEdit.folderId);
        setSourceArticleIds(noteToEdit.sourceArticleIds || []);
      } else if (initialNoteContent) {
        setTitle(initialNoteContent.title);
        setContent(initialNoteContent.content);
        setFolderId(noteFolders.length > 0 ? noteFolders[0].id : '');
        setSourceArticleIds(initialNoteContent.sourceArticleIds || []);
      } else {
        setTitle('');
        setContent('');
        setFolderId(noteFolders.length > 0 ? noteFolders[0].id : '');
        setSourceArticleIds([]);
      }
      setShowNewFolderInput(false);
      setNewFolderName('');
      setCopyStatus('idle');
      setMode('edit');
      setTimeout(() => titleInputRef.current?.focus(), 100);
    }
  }, [isNoteEditorModalOpen, noteToEdit, initialNoteContent, noteFolders]);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (copyDropdownRef.current && !copyDropdownRef.current.contains(event.target as Node)) {
        setIsCopyDropdownOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  useEffect(() => {
    if (copyStatus !== 'idle') {
      const timer = setTimeout(() => setCopyStatus('idle'), 2000);
      return () => clearTimeout(timer);
    }
  }, [copyStatus]);

  const handleSave = async () => {
    if (!title.trim()) {
      alert('Title cannot be empty.');
      return;
    }
    if (!folderId) {
      alert('Please select or create a folder.');
      return;
    }

    await handleSaveNote(
      {
        title: title.trim(),
        content,
        folderId,
        sourceArticleIds,
      },
      noteToEdit?.id
    );

    handleCloseNoteEditor();
  };

  const handleAddNewFolder = async () => {
    if (!newFolderName.trim()) return;
    const newFolder = await handleAddNoteFolder(newFolderName.trim());
    setFolderId(newFolder.id);
    setShowNewFolderInput(false);
    setNewFolderName('');
  };

  const markdownToHtml = (markdown: string): string => {
    if (!markdown) return '';
    let html = '';
    let inList = false;

    const escapeHtml = (unsafe: string) =>
      unsafe
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');

    const inlineReplacer = (text: string) => {
      const parts = text.split(/(\[.*?\]\(.*?\))|(\*\*.*?\*\*)/g).filter(Boolean);
      return parts
        .map(part => {
          const linkMatch = part.match(/\[(.*?)\]\((.*?)\)/);
          if (linkMatch) {
            const url = escapeHtml(linkMatch[2]);
            const linkText = escapeHtml(linkMatch[1]);
            return `<a href="${url}" target="_blank" rel="noopener noreferrer">${linkText}</a>`;
          }
          const boldMatch = part.match(/\*\*(.*?)\*\*/);
          if (boldMatch) {
            return `<strong>${escapeHtml(boldMatch[1])}</strong>`;
          }
          return escapeHtml(part);
        })
        .join('');
    };

    markdown.split('\n').forEach(line => {
      const imageMatch = line.match(/^!\[(.*?)\]\((.*?)\)$/);
      if (imageMatch) {
        if (inList) {
          html += '</ul>';
          inList = false;
        }
        html += `<img src="${escapeHtml(imageMatch[2])}" alt="${escapeHtml(imageMatch[1])}" style="max-width: 100%; height: auto; border-radius: 8px; margin: 1em 0;" />`;
      } else if (line.startsWith('## ')) {
        if (inList) {
          html += '</ul>';
          inList = false;
        }
        html += `<h2>${inlineReplacer(line.substring(3))}</h2>`;
      } else if (line.startsWith('### ')) {
        if (inList) {
          html += '</ul>';
          inList = false;
        }
        html += `<h3>${inlineReplacer(line.substring(4))}</h3>`;
      } else if (line.startsWith('- ')) {
        if (!inList) {
          html += '<ul>';
          inList = true;
        }
        html += `<li>${inlineReplacer(line.substring(2))}</li>`;
      } else if (line.trim() === '---') {
        if (inList) {
          html += '</ul>';
          inList = false;
        }
        html += '<hr>';
      } else if (line.trim() === '') {
        if (inList) {
          html += '</ul>';
          inList = false;
        }
        html += '<br>';
      } else {
        if (inList) {
          html += '</ul>';
          inList = false;
        }
        html += `<p>${inlineReplacer(line)}</p>`;
      }
    });
    if (inList) {
      html += '</ul>';
    }

    return html;
  };

  const handleCopy = async (format: 'markdown' | 'html') => {
    setIsCopyDropdownOpen(false);
    try {
      if (format === 'markdown') {
        await navigator.clipboard.writeText(content);
      } else {
        // html
        const html = markdownToHtml(content);
        const blob = new Blob([html], { type: 'text/html' });
        const clipboardItem = new ClipboardItem({ 'text/html': blob });
        await navigator.clipboard.write([clipboardItem]);
      }
      setCopyStatus('copied');
    } catch (err) {
      console.error('Failed to copy: ', err);
      setCopyStatus('error');
    }
  };

  if (!isNoteEditorModalOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[60]">
      <div className="bg-gray-800 rounded-lg shadow-xl w-full max-w-3xl h-[90vh] m-4 flex flex-col">
        <header className="p-4 border-b border-gray-700 flex-shrink-0 flex justify-between items-center">
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <SaveIcon className="w-6 h-6 text-indigo-400" />
            {noteToEdit ? 'Edit Note' : 'Save as Note'}
          </h2>
          <button onClick={handleCloseNoteEditor} className="text-gray-400 hover:text-white">
            <XIcon className="w-6 h-6" />
          </button>
        </header>
        <div className="flex-grow p-6 flex flex-col gap-4 min-h-0">
          <input
            ref={titleInputRef}
            type="text"
            value={title}
            onChange={e => setTitle(e.target.value)}
            placeholder="Note Title"
            className="w-full bg-gray-900 border border-gray-700 text-white rounded-md p-3 text-lg font-semibold focus:ring-2 focus:ring-indigo-500 outline-none"
          />
          <div className="flex items-center gap-2">
            <FolderIcon className="w-5 h-5 text-gray-400" />
            <select
              value={folderId}
              onChange={e => setFolderId(e.target.value)}
              className="bg-gray-700 text-white font-semibold py-2 pl-3 pr-8 rounded-md appearance-none focus:outline-none focus:ring-2 focus:ring-indigo-500"
            >
              {noteFolders.length === 0 && (
                <option value="" disabled>
                  No folders yet
                </option>
              )}
              {noteFolders.map(folder => (
                <option key={folder.id} value={folder.id}>
                  {folder.name}
                </option>
              ))}
            </select>
            <button
              onClick={() => setShowNewFolderInput(p => !p)}
              className="p-2 rounded-full hover:bg-gray-700"
            >
              <PlusIcon className="w-5 h-5 text-gray-300" />
            </button>
            {showNewFolderInput && (
              <div className="flex items-center gap-2">
                <input
                  type="text"
                  value={newFolderName}
                  onChange={e => setNewFolderName(e.target.value)}
                  placeholder="New Folder Name"
                  className="bg-gray-900 border border-gray-700 text-white rounded-md px-2 py-1.5 text-sm focus:ring-1 focus:ring-indigo-500 outline-none"
                />
                <button
                  onClick={handleAddNewFolder}
                  className="px-3 py-1.5 text-sm font-semibold bg-indigo-600 rounded-md hover:bg-indigo-500"
                >
                  Create
                </button>
              </div>
            )}
          </div>

          <div className="flex items-center border-b border-gray-700">
            <button
              onClick={() => setMode('edit')}
              className={`px-4 py-2 text-sm font-semibold ${mode === 'edit' ? 'text-white border-b-2 border-indigo-500' : 'text-gray-400'}`}
            >
              Edit
            </button>
            <button
              onClick={() => setMode('view')}
              className={`px-4 py-2 text-sm font-semibold ${mode === 'view' ? 'text-white border-b-2 border-indigo-500' : 'text-gray-400'}`}
            >
              Preview
            </button>
          </div>

          {mode === 'edit' ? (
            <textarea
              value={content}
              onChange={e => setContent(e.target.value)}
              placeholder="Note content (Markdown is supported)..."
              className="w-full h-full bg-gray-900 border border-gray-700 text-white rounded-md p-3 focus:ring-2 focus:ring-indigo-500 outline-none flex-grow resize-none"
            />
          ) : (
            <div className="w-full h-full bg-gray-900 border border-gray-700 rounded-md p-3 overflow-y-auto">
              <SimpleMarkdownRenderer content={content} />
            </div>
          )}
        </div>
        <footer className="p-4 border-t border-gray-700 flex-shrink-0 flex justify-between items-center">
          <div className="relative" ref={copyDropdownRef}>
            <button
              onClick={() => setIsCopyDropdownOpen(p => !p)}
              className="flex items-center gap-2 px-4 py-2 rounded-md bg-gray-700 text-gray-300 hover:bg-gray-600 font-semibold"
            >
              {copyStatus === 'idle' && (
                <>
                  <CopyIcon className="w-5 h-5" /> Copy Note
                </>
              )}
              {copyStatus === 'copied' && (
                <>
                  <ClipboardCheckIcon className="w-5 h-5" /> Copied!
                </>
              )}
              {copyStatus === 'error' && 'Error!'}
              <ChevronDownIcon
                className={`w-4 h-4 ml-1 transition-transform ${isCopyDropdownOpen ? 'rotate-180' : ''}`}
              />
            </button>
            {isCopyDropdownOpen && (
              <div className="absolute bottom-full mb-2 w-48 bg-gray-700 rounded-md shadow-lg z-10 border border-gray-600 p-1">
                <button
                  onClick={() => handleCopy('html')}
                  className="w-full text-left flex items-center gap-2 px-3 py-2 text-sm rounded-md text-gray-200 hover:bg-indigo-600 hover:text-white"
                >
                  Copy as Rich Text
                </button>
                <button
                  onClick={() => handleCopy('markdown')}
                  className="w-full text-left flex items-center gap-2 px-3 py-2 text-sm rounded-md text-gray-200 hover:bg-indigo-600 hover:text-white"
                >
                  Copy as Markdown
                </button>
              </div>
            )}
          </div>
          <div className="flex gap-4">
            <button
              onClick={handleCloseNoteEditor}
              className="px-4 py-2 rounded-md text-gray-300 bg-gray-700 hover:bg-gray-600"
            >
              Cancel
            </button>
            <button
              onClick={handleSave}
              className="px-6 py-2 rounded-md bg-indigo-600 text-white font-semibold hover:bg-indigo-500"
            >
              Save Note
            </button>
          </div>
        </footer>
      </div>
    </div>
  );
};
